# Generated by Django 3.2.25 on 2024-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240324_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='legende',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
