# Generated by Django 3.2.25 on 2024-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20240325_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='legende',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
